name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed, reopened]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Setup PNPM
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
      
      # Setup Turbo cache
      - name: Setup Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      
      # Cache Next.js build
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            apps/client/.next/cache
            apps/admin/.next/cache
          key: ${{ runner.os }}-nextjs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      # Build apps and cache output
      - name: Build apps
        run: pnpm install && pnpm turbo build
      
      # Save build output as artifact
      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            apps/client/.next
            apps/admin/.next
            apps/*/public
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Download build output
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build-output
      
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:cache,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}