name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed, reopened]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
      
      # Setup Turbo cache
      - name: Setup Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      
      # Cache Next.js build
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            apps/client/.next/cache
            apps/admin/.next/cache
          key: ${{ runner.os }}-nextjs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      # Install and build
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build applications
        run: pnpm turbo build
      
      # Prepare artifact
      - name: Prepare artifact
        run: |
          mkdir -p artifact
          # Copy Next.js builds
          cp -r apps/client/.next artifact/client-next
          cp -r apps/admin/.next artifact/admin-next
          
          # Copy public directories (only if they exist)
          if [ -d "apps/client/public" ]; then
            cp -r apps/client/public artifact/client-public
          fi
          if [ -d "apps/admin/public" ]; then
            cp -r apps/admin/public artifact/admin-public
          fi
          
          # Copy package files
          cp pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json artifact/
          cp apps/client/package.json artifact/client-package.json
          cp apps/admin/package.json artifact/admin-package.json
      
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: artifact
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: artifact
      
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/prompt_oven_fe_testbed:cache,mode=max